export interface TimezoneOption {
  value: string;
  label: string;
}

export const TIMEZONE_OPTIONS: TimezoneOption[] = [
  { value: 'Europe/Kaliningrad', label: 'Калининград (UTC+2) — Europe/Kaliningrad' },
  { value: 'Europe/Moscow', label: 'Москва (UTC+3) — Europe/Moscow' },
  { value: 'Europe/Samara', label: 'Самара (UTC+4) — Europe/Samara' },
  { value: 'Asia/Yekaterinburg', label: 'Екатеринбург (UTC+5) — Asia/Yekaterinburg' },
  { value: 'Asia/Omsk', label: 'Омск (UTC+6) — Asia/Omsk' },
  { value: 'Asia/Novosibirsk', label: 'Новосибирск (UTC+7) — Asia/Novosibirsk' },
  { value: 'Asia/Krasnoyarsk', label: 'Красноярск (UTC+7) — Asia/Krasnoyarsk' },
  { value: 'Asia/Irkutsk', label: 'Иркутск (UTC+8) — Asia/Irkutsk' },
  { value: 'Asia/Chita', label: 'Чита (UTC+9) — Asia/Chita' },
  { value: 'Asia/Yakutsk', label: 'Якутск (UTC+9) — Asia/Yakutsk' },
  { value: 'Asia/Vladivostok', label: 'Владивосток (UTC+10) — Asia/Vladivostok' },
  { value: 'Asia/Sakhalin', label: 'Сахалин (UTC+11) — Asia/Sakhalin' },
  { value: 'Asia/Magadan', label: 'Магадан (UTC+11) — Asia/Magadan' },
  { value: 'Asia/Kamchatka', label: 'Камчатка (UTC+12) — Asia/Kamchatka' },
  { value: 'Europe/London', label: 'Лондон (UTC+0/+1) — Europe/London' },
  { value: 'Europe/Dublin', label: 'Дублин (UTC+0/+1) — Europe/Dublin' },
  { value: 'Europe/Lisbon', label: 'Лиссабон (UTC+0/+1) — Europe/Lisbon' },
  { value: 'Europe/Berlin', label: 'Берлин (UTC+1/+2) — Europe/Berlin' },
  { value: 'Europe/Paris', label: 'Париж (UTC+1/+2) — Europe/Paris' },
  { value: 'Europe/Madrid', label: 'Мадрид (UTC+1/+2) — Europe/Madrid' },
  { value: 'Europe/Rome', label: 'Рим (UTC+1/+2) — Europe/Rome' },
  { value: 'Europe/Amsterdam', label: 'Амстердам (UTC+1/+2) — Europe/Amsterdam' },
  { value: 'Europe/Brussels', label: 'Брюссель (UTC+1/+2) — Europe/Brussels' },
  { value: 'Europe/Prague', label: 'Прага (UTC+1/+2) — Europe/Prague' },
  { value: 'Europe/Warsaw', label: 'Варшава (UTC+1/+2) — Europe/Warsaw' },
  { value: 'Europe/Athens', label: 'Афины (UTC+2/+3) — Europe/Athens' },
  { value: 'Europe/Helsinki', label: 'Хельсинки (UTC+2/+3) — Europe/Helsinki' },
  { value: 'Europe/Kyiv', label: 'Киев (UTC+2/+3) — Europe/Kyiv' },
  { value: 'Europe/Istanbul', label: 'Стамбул (UTC+3) — Europe/Istanbul' },
  { value: 'Asia/Dubai', label: 'Дубай (UTC+4) — Asia/Dubai' },
  { value: 'Asia/Tbilisi', label: 'Тбилиси (UTC+4) — Asia/Tbilisi' },
  { value: 'Asia/Baku', label: 'Баку (UTC+4) — Asia/Baku' },
  { value: 'Asia/Yerevan', label: 'Ереван (UTC+4) — Asia/Yerevan' },
  { value: 'Asia/Karachi', label: 'Карачи (UTC+5) — Asia/Karachi' },
  { value: 'Asia/Almaty', label: 'Алматы (UTC+5) — Asia/Almaty' },
  { value: 'Asia/Tashkent', label: 'Ташкент (UTC+5) — Asia/Tashkent' },
  { value: 'Asia/Kolkata', label: 'Дели/Мумбаи (UTC+5:30) — Asia/Kolkata' },
  { value: 'Asia/Dhaka', label: 'Дакка (UTC+6) — Asia/Dhaka' },
  { value: 'Asia/Bangkok', label: 'Бангкок (UTC+7) — Asia/Bangkok' },
  { value: 'Asia/Ho_Chi_Minh', label: 'Хошимин (UTC+7) — Asia/Ho_Chi_Minh' },
  { value: 'Asia/Jakarta', label: 'Джакарта (UTC+7) — Asia/Jakarta' },
  { value: 'Asia/Shanghai', label: 'Шанхай (UTC+8) — Asia/Shanghai' },
  { value: 'Asia/Hong_Kong', label: 'Гонконг (UTC+8) — Asia/Hong_Kong' },
  { value: 'Asia/Singapore', label: 'Сингапур (UTC+8) — Asia/Singapore' },
  { value: 'Asia/Seoul', label: 'Сеул (UTC+9) — Asia/Seoul' },
  { value: 'Asia/Tokyo', label: 'Токио (UTC+9) — Asia/Tokyo' },
  { value: 'Australia/Perth', label: 'Перт (UTC+8) — Australia/Perth' },
  { value: 'Australia/Adelaide', label: 'Аделаида (UTC+9:30/+10:30) — Australia/Adelaide' },
  { value: 'Australia/Sydney', label: 'Сидней (UTC+10/+11) — Australia/Sydney' },
  { value: 'Pacific/Auckland', label: 'Окленд (UTC+12/+13) — Pacific/Auckland' },
  { value: 'Pacific/Fiji', label: 'Фиджи (UTC+12) — Pacific/Fiji' },
  { value: 'Africa/Cairo', label: 'Каир (UTC+2) — Africa/Cairo' },
  { value: 'Africa/Johannesburg', label: 'Йоханнесбург (UTC+2) — Africa/Johannesburg' },
  { value: 'Africa/Nairobi', label: 'Найроби (UTC+3) — Africa/Nairobi' },
  { value: 'America/St_Johns', label: 'Сент-Джонс (UTC-3:30/-2:30) — America/St_Johns' },
  { value: 'America/Halifax', label: 'Галифакс (UTC-4/-3) — America/Halifax' },
  { value: 'America/New_York', label: 'Нью-Йорк (UTC-5/-4) — America/New_York' },
  { value: 'America/Toronto', label: 'Торонто (UTC-5/-4) — America/Toronto' },
  { value: 'America/Chicago', label: 'Чикаго (UTC-6/-5) — America/Chicago' },
  { value: 'America/Denver', label: 'Денвер (UTC-7/-6) — America/Denver' },
  { value: 'America/Los_Angeles', label: 'Лос-Анджелес (UTC-8/-7) — America/Los_Angeles' },
  { value: 'America/Anchorage', label: 'Анкоридж (UTC-9/-8) — America/Anchorage' },
  { value: 'Pacific/Honolulu', label: 'Гонолулу (UTC-10) — Pacific/Honolulu' },
  { value: 'America/Mexico_City', label: 'Мехико (UTC-6/-5) — America/Mexico_City' },
  { value: 'America/Bogota', label: 'Богота (UTC-5) — America/Bogota' },
  { value: 'America/Lima', label: 'Лима (UTC-5) — America/Lima' },
  { value: 'America/Santiago', label: 'Сантьяго (UTC-4/-3) — America/Santiago' },
  { value: 'America/Sao_Paulo', label: 'Сан-Паулу (UTC-3) — America/Sao_Paulo' },
  { value: 'America/Buenos_Aires', label: 'Буэнос-Айрес (UTC-3) — America/Buenos_Aires' },
];
